//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.13 at 07:34:22 PM IST 
//


package com.rssoftware.ou.schema.cbs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CbsApiNames.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CbsApiNames">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Debit"/>
 *     &lt;enumeration value="Credit"/>
 *     &lt;enumeration value="Register MPIN"/>
 *     &lt;enumeration value="Req OTP"/>
 *     &lt;enumeration value="Change MPIN"/>
 *     &lt;enumeration value="Forget MPIN"/>
 *     &lt;enumeration value="Balance Enquiry"/>
 *     &lt;enumeration value="List Account"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CbsApiNames", namespace = "http://rssoftware.com/upiint/schema/")
@XmlEnum
public enum CbsApiNames {

    @XmlEnumValue("Debit")
    DEBIT("Debit"),
    @XmlEnumValue("Credit")
    CREDIT("Credit"),
    @XmlEnumValue("Register MPIN")
    REGISTER_MPIN("Register MPIN"),
    @XmlEnumValue("Req OTP")
    REQ_OTP("Req OTP"),
    @XmlEnumValue("Change MPIN")
    CHANGE_MPIN("Change MPIN"),
    @XmlEnumValue("Forget MPIN")
    FORGET_MPIN("Forget MPIN"),
    @XmlEnumValue("Balance Enquiry")
    BALANCE_ENQUIRY("Balance Enquiry"),
    @XmlEnumValue("List Account")
    LIST_ACCOUNT("List Account");
    private final String value;

    CbsApiNames(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CbsApiNames fromValue(String v) {
        for (CbsApiNames c: CbsApiNames.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
