package org.npci.bbps.test;

public enum RequestType {
	BILL_FETCH_REQUEST,BILL_PAYMENT_REQUEST,
	BILL_FETCH_RESPONSE,BILL_PAYMENT_RESPONSE,	
	BILLER_FETCH_REQUEST, BILLER_FETCH_RESPONSE,
	DIAGNOSTIC_REQUEST, FRAW
}
