/**
 * 
 */
package com.rssoftware.ou.common;

import java.io.Serializable;

/**
 * @author rsdpp
 *
 */
public enum ErrorCode implements Serializable{
	DUPLICATE_REQ,
	AMOUNT_CAP_EXCEEDED,
	NET_DEBIT_CAP_EXCEEDED,
	REQ_NOT_FOUND,
	MALFORMED,
	TRANSACTION_ID_MISMATCH,
	VALIDATION_ERR,
	SYSTEM_EXCEPTION,
	TIMEOUT,
	ILLEGAL_OPERATION,
	CREDENTIALS_NOT_PRESENT,
	AMOUNT_OR_CURRENCY_MISMATCH,
	EXTERNAL_ERROR,
	CRYPTO_ERROR,
	TXNID_AMT_MISMATCH_IN_CRED,
	CHECKSUM_FAILED,
	
	RISK_THRESHOLD_EXCEEDED,
	
	PSP_NOT_REGISTERED,
	REQ_AUTH_ACK_NOT_RECEIVED,
	REQ_AUTH_DECLINED ,
	REQ_AUTH_TIMEOUT ,
	//will be handled in web part
	REQ_AUTH_NOT_FOUND ,
	
	CM_REQ_DECLINED ,
	CM_REQ_TIMEOUT ,
	CM_REQ_ACK_NOT_RECEIVED ,
	CM_URL_NOT_FOUND ,
	PSP_REQ_CR_PAY_ACK_NOT_RECVD ,
	PSP_REQ_DR_PAY_ACK_NOT_RECVD ,
	PSP_NO_RESPONSE ,
	PSP_NOT_AVAILABLE ,
	
	// following will be used in RespPay error Code
	ADDR_RESL_FAILED,
	DR_FAILED,
	CR_FAILED,
	CR_REVERT_FAILED,
	DR_REVERT_FAILED,
	REVERTED,
	
	//Credit flow
	ALREADY_RECEIVED_RESPONSE,
	ALREADY_SENT_REQUEST,
	ALREADY_SENT_REVERSAL, 
	ALREADY_SENT_RESPONSE,
	
	ALREADY_FAILED_TRANSACTION,
	IMPS_PROCESSING_FAILED_IN_UPI,
	IMPS_SIGNED_OFF,
	IMPS_TXN_ALREADY_PROCESSED,
	IMPS_DECLINE,
	FRM_SIGNED_OFF,
	FRM_PROCESSING_FAILED_IN_UPI,
	REQ_CR_NOT_FOUND,
	REQ_DR_NOT_FOUND, 
	TRANSACTION_ID_NOT_PRESENT,
	REQ_MSG_ID_NOT_PRESENT, 
	IFSC_NOT_PRESENT, 
	REQ_REFUND_NOT_FOUND,
	PAYEE_MISMATCH,
	PAYEE_AMT_MISMATCH,
	PAYER_AMT_MISMATCH,
	PAYEE_ADDR_MISMATCH,
	PAYER_ADDR_MISMATCH,
	PAYEE_INFO_MISMATCH,
	PAYER_INFO_MISMATCH,
	//File upload specific error codes
	FILE_EMPTY,
	UNEXPECTED_FILE_TYPE,
	DATABASE_ERROR,
	// Upi int specific error codes
	TXN_CONFIRM_ACK_NOT_RECVD, 
	RESP_AUTH_ACK_NOT_RECVD, 
	DEBIT_RESP_ACK_NOT_RECVD, 
	CREDIT_RESP_ACK_NOT_RECVD,
	DR_REVERSAL_RESP_ACK_NOT_RECVD, 
	CR_REVERSAL_RESP_ACK_NOT_RECVD,
	INVALID_BILLER,

	// Error key in error_codes table
	BILL_NOT_AVAILABLE,
	DUE_DATE_EXPIRED,
	INVALID_BILL_DETAILS,
	INVALID_CUSTOMER_PARAM,
	NO_BILL_DUE,
	REPEAT_PAYMENT,
	HEAD_REQUIRED_ACK,
	TXN_REQUIRED_ACK,
	INVALID_BILLER_ACK,
	BILLDETAILS_NULL_ACK,
	BILLER_NULL_ACK,
	BILLERID_NULL_ACK,
	REQUEST_INVALID_ACK,
	DUPLICATE_REFID_ACK,
	PAYMENT_FAILED, 
	//user
	USER_NOT_FOUND,
	WRONG_PASSWORD,
	SYSTEM_ERROR
}