package com.rssoftware.ou.common;

public enum TypeOfBatch {
	RECONCILIATION, TXN_REPORT, BILLER_FETCH,BILLER_FETCH_BY_PARAMETER, HEARTBEAT, BILLER_SAVE, BILL_FETCH_REQUEST, BILL_PAYMENT, BILL_FETCH, BILL_PAYMENT_REPORT, BOU_BLR_RECON, FIN_RECON, 
	CU_AGENT_APPROVAL_REQ, ALL_CU_APPROVED_AGENTS_FETCH;
	
}
